name: pharokka_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcbio-gff
  - biopython>=1.78
  - phanotate>=1.5.0
  - mmseqs2>=13.45111
  - trnascan-se>=2.0.9
  - prodigal>=2.6.3
  - minced>=0.4.2
  - aragorn>=1.2.41
  - unzip

