name: pharokka_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcbio-gff
  - biopython >=1.78,<1.81
  - phanotate >=1.5.0
  - mmseqs2 ==13.45111
  - trnascan-se >=2.0.9
  - minced >=0.4.2
  - aragorn >=1.2.41
  - mash >=2.2
  - pyrodigal >=2.0.1
  - pycicrlize >=0.3.1

