site_name: pharokka
site_url: "https://github.com/gbouras13/pharokka"
site_author: George Bouras
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - python
nav:
    - ABOUT:
      - Overview: index.md
      - Why Use pharokka?: reasons.md
    - RUNNING:
      - Install: install.md
      - Usage: run.md
      - Benchmarking: benchmarking.md
    - OUTPUT:
      - Output: output.md

